lib/cuota_proto_web/router.ex
defmodule CuotaProtoWeb.Router do
  use CuotaProtoWeb, :router

  import CuotaProtoWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CuotaProtoWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CuotaProtoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CuotaProtoWeb.Telemetry


    end
  end

  ## Authentication routes

  scope "/", CuotaProtoWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CuotaProtoWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    put "/users/settings/delete", UserSettingsController, :delete
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    resources "/matters", MatterController
    post "/", PageController, :add_matter

    get "/to", PageController, :to

    delete "/delete", PageController, :delete
    delete "/all_delete", PageController, :all_delete

    post "/path", PageController, :path

    resources "/fileuploads", FileUploadController, only: [:index, :create, :new]
    get "/fileuploads/set", FileUploadController, :set
    get "/fileuploads/delete", FileUploadController, :delete
    post "/fileuploads/preview", FileUploadController, :preview
    get "/fileuploads/cancel_preview", FileUploadController, :cancel_preview
    get "/fileuploads/all", FileUploadController, :all
    get "/fileuploads/receive", FileUploadController, :receive

    resources "/messages", MessageController
  end

  scope "/", CuotaProtoWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/cuota_proto_web/views/layout_view.ex
defmodule CuotaProtoWeb.LayoutView do
  use CuotaProtoWeb, :view
end

lib/cuota_proto_web/templates/layout/_user_menu.html.eex
<div class="acunt">
<%= if @current_user do %>
  <div><%= @current_user.email %></div>
  <div><%= link "設定", to: Routes.user_settings_path(@conn, :edit) %></div>
  <div><%= link "ログアウト", to: Routes.user_session_path(@conn, :delete), method: :delete %></div>
<% else %>
  <div><%= link "新規作成", to: Routes.user_registration_path(@conn, :new) %></div>
  <div><%= link "ログイン", to: Routes.user_session_path(@conn, :new) %></div>
<% end %>
</div>

lib/cuota_proto_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CuotaProto</title>
    <link rel="shortcut icon" href="/images/cuotaimg/Cuota_logo01.png" type="image/x-icon">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <!-- CSS Reset -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

    <!-- Milligram CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
  </head>
  <body>
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="row">
            <h3 class="column column-15 headertop cuota_img"><%= link img_tag(Routes.static_path(@conn, "/images/cuotaimg/Cuota_logo01.png")), to: Routes.page_path(@conn, :index)%></h3>
            <%= if @current_user do %>
            <h3 class="column headertop header_text"><%= link "新規作成", to: Routes.file_upload_path(@conn, :new)%></h3>
            <h3 class="column headertop header_text"><%= link "送信履歴", to: Routes.file_upload_path(@conn, :index)%></h3>
            <h3 class="column headertop header_text"><%= link "受信履歴", to: Routes.file_upload_path(@conn, :receive) %></h3>
            <% end %>
            <div class="column"></div>
          </div>
            <div class="acuntmenu"><%= render "_user_menu.html", assigns %></div>
        </div>
      </div>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>